### PR TITLE
Rename communication classes + add one-way communication

### LINKED ISSUE #4: Change server URL property type to `List<String>`
A list of server URLs instead of just one server.

### PR DESCRIPTION
**Pull request by corcoja**
# Rename communication classes + add one-way communication

## Description

The purpose of this PR is mainly for renaming the `TinCanCommunication` class to a more appropriate `PubSubTunnel`. Additionally, `PubOnlyTunnel` has been added as a one-way communication (you can only publish messages).

### New Design

There are now three main components that facilitate communication through NATS server:

1. `ConnectionPrimer` - same as before with more tweaks, updates and bug fixes.
2. `PubSubTunnel` - the communication "tunnel" which allows publishing messages and listening for new ones. The `PubSubTunnel` object supports one publisher and one listener at a time.
3. `PubOnlyTunnel` - the communication "tunnel" which allows only publishing messages.

To create a `PubSubTunnel` object, you'll need the same [`StreamConfiguration`][2] and [`ConsumerConfiguration`][3] from the [`jnats`][1] library, and a `ConnectionPrimer` from `lib.eventing`:

```java
PubSubTunnel pubSubTunnel = new PubSubTransceiver(connectionPrimer,
                                                  streamConfiguration,
                                                  consumerConfiguration,
                                                  pubSubConfiguration);
```

Messages can be published like this:

```java
String subject = "test.subject";
String message = "This is a test message!"
pubSubTunnel.publish(subject, message);
```

Same when listening for new messages:

```java
pubSubTunnel.subscribe(new SubHandler() {
  @Override
  public void newMessageReceived(PubSubTunnel pubSubTunnel, String subject, String message) {
    System.out.println("Received message with subject: " + subject + "\nMessage:\n" + message);
  }
});
```

To create a `PubOnlyTunnel` object, you'll need [`StreamConfiguration`][2] from the [`jnats`][1] library, and a `ConnectionPrimer` from `lib.eventing`:

```java
PubOnlyTunnel pubOnlyTunnel = new PubTransmitter(connectionPrimer,
                                                 streamConfiguration,
                                                 pubOnlyConfiguration);
```

Messages can be published like this:

```java
String subject = "test.subject";
String message = "This is a test message!"
pubOnlyTunnel.publish(subject, message);
```

### New

- `PubOnlyTunnel` object that create a communication channel that can be used one-way only. ➡️
- Unit tests and integration tests. ❎✅
- Javadoc. ☕️📚

### Changed

- `PubSubTunnel` object that create a communication channel that can be used both ways. ↔️

### Removed

- `TinCanCommunication` and all other related classes. ❌

[1]: https://github.com/nats-io/nats.java "NATS Java Client"
[2]: https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/api/StreamConfiguration.java "StreamConfiguration.java"
[3]: https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/api/ConsumerConfiguration.java "ConsumerConfiguration.java"

### CODE REVIEW

**Comment by corcoja** [comment]
This is the last major PR for this library before releasing Flow with NATS Jetstream integration.

**Comment by corcoja** [comment]
This PR implements every requirement from boomerang-io/roadmap#255.

**Comment by tlawrie** [comment]
Wow. This is a big PR. It will take me a little while to work through the review. But well done.

What made you decide in the end to change from TinCan to PubSubTunnel?

Also I really like the detail that you put into your PRs. Thank you!

**Comment by corcoja** [comment]
@tlawrie, the name. I think `PubSub` is a better name, since it tells that this lib **PUB**lishes something and **SUB**scribes to something.

**Comment by tlawrie** [comment]
> @tlawrie, the name. I think `PubSub` is a better name, since it tells that this lib **PUB**lishes something and **SUB**scribes to something.

Fair enough. It is definitely not as fun! But you are right, it does convey the purpose.

**Review by tlawrie — APPROVED** [review]

**Comment by tlawrie** [comment]
Hi @corcoja ive approved. Fantastic coding.

One question. It mentions the NATSProperties. When a service implements this lib, do we have a documented example of the parameters or is simply the same as the NATSProperties with no additional format etc?

**Review by marcusdroy — APPROVED** [review]

**Comment by corcoja** [comment]
> One question. It mentions the NATSProperties. When a service implements this lib, do we have a documented example of the parameters or is simply the same as the NATSProperties with no additional format etc?

Old javadoc, NATSProperties no longer needed. Will remove any reference to it.

**Pull request merged**
